db:
  image: mongo
  ports:
    - "27017:27017"
  entrypoint: /entrypoint.sh mongo
  command: "mongoimport --db test --collection users --drop --file user_list.json"
web:
  build: .
  command: node app.js
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
  environment:
  MONGODB: $MONGO_URL
  PORT: 5000
